name: all_box_devtool_example
description: Example app used to test the all_box DevTools extension locally.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  all_box: ^0.6.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_box_devtool:
    path: ..
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
